---
title: Maryana Sales, floreando na web
timezone: America/Sao_Paulo
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: pages
  values:
    layout: page
- scope:
    path: ''
    type: posts
  values:
    layout: post
description: Designer e desenvolvedora santista, que através da criatividade e linhas de código espalha um pouco de si por aí.
baseurl: ""
url: http://maryanasales.com.br
markdown: kramdown
sass:
  style: compressed
exclude:
- node_modules
- desktop.ini
- gulpfile.js
- npm-debug.log
- package.json
